updated readme - wrapper note
dotkernel/dot-debugbar pull request #26
Opened 2024-06-27 23:02 UTC by bidi47

2024-06-28 04:12 UTC, alexmerlin requested changes

2024-06-28 04:12 UTC, alexmerlin commented on README.md
>  DotKernel's debug bar built on top of [maximebf/php-debugbar](https://github.com/maximebf/php-debugbar).
```suggestion
## dot-debugbar badges
```

2024-06-28 09:28 UTC, arhimede requested changes
Please add in documentation the line with wrapper

2024-06-28 09:32 UTC, arhimede requested changes
Please add in documentation the line with wrapper
without the line
> [!IMPORTANT]

2024-06-28 13:17 UTC, bidi47 commented on README.md
>  DotKernel's debug bar built on top of [maximebf/php-debugbar](https://github.com/maximebf/php-debugbar).
replaced with wrapper note

2024-06-29 04:02 UTC, alexmerlin approved these changes

2024-06-29 09:58 UTC, arhimede approved these changes

2024-06-29 09:58 UTC, merged